[[redirects]]
  from = "/arcade/ai-pong"
  to = "/arcade/ai-pong/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[build]
  publish = "dist"
  command = "npm run build"
